# Basic
title: lavic Liu
subtitle: like coding,travelling 
welcome_message: <a href="" target="_blank">xmu,student</a>
description: 不忘初心.
creator: <a href="http://github.com/laviclu">@lavic</a>

url: "http://lavic.cc"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: hupu, description: Thunder, url: 'https://bbs.hupu.com/thunder'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: lavicliu
    # duoshuo: 
    
# Social
social:
    weibo: lrdvr12
    github: laviclu
    instagram: lavic.liu
    
    mail: lavic.liu@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
gems:
 - jemoji
